# Generated by Django 5.0.1 on 2025-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('qrcode', models.ImageField(upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
