# Generated by Django 5.0.1 on 2025-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='upi_id',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='qrcode',
            field=models.ImageField(upload_to='qr_codes'),
        ),
    ]
